### ISSUE TITLE
code for IFFT

### ISSUE THREAD

**Issue by petercmh01** [raultapia/efft#1]
Hello : ) thanks for the great work. I am just wondering if there is any code example for IFFT (i.e., reconstructing the events)?

**Comment by softword-tt** [comment]
I also have this request, thx the authors' great work again!

**Comment by raultapia** [comment]
Hello there!
Thanks for your interest in this work.

Transforming from the frequency domain to the spatial domain is quite more challenging. Each change (event) in the spatial domain requires updating the NxN elements in the frequency domain. That’s why we use the tree structure based on FFT decomposition (you can check out the paper for more info).

However, every change in the frequency domain also affects the NxN elements in the spatial domain if you want to perform the inverse transform. Therefore, directly using the eFFT approach to compute the inverse of the result of an operation in the frequency domain would be just as efficient as a standard inverse FFT (and that’s what is done for some evaluations).

Some approaches can be applied to specific cases (for example, a low-pass filter that only requires inverse-transforming a few components). However, a more general solution is something I’m currently working on, so **please stay tuned**!

I will close the issue for now and reopen it if necessary.
